spring:
  application:
    name: HotelBookingApp
  datasource:
    url: jdbc:postgresql://localhost:5432/Hotel_Booking_Application
    username: postgres
    password: pg123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  mail:
    username: osasuomo@yahoo.com
    password: wdrl qpit htil njal
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


