spring:
  application:
    name: HotelBookingApp
  datasource:
    url: jdbc:postgresql://localhost:5432/Hotel_Booking_Application
    username: postgres
    password: pg123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


